"""End-to-end Diagnose -> Retrieve -> Generate -> Verify -> Learn orchestration."""

from __future__ import annotations

from pathlib import Path

from autoharness.evolution import EvolutionPipeline
from autoharness.generation import PatchGenerator
from autoharness.ledger import RepairLedger
from autoharness.models import (
    AgentTrace,
    AutoFixPipelineResult,
    PatchGenerationContext,
    PatchVerificationPlan,
    RepairExperience,
    SkillRecommendationResult,
)
from autoharness.registry import SkillRecommender


class AutoFixPipeline:
    """Compose a patch provider with deterministic safety and evolution layers."""

    def __init__(
        self,
        generator: PatchGenerator,
        ledger: RepairLedger,
        skill_directory: str | Path,
    ) -> None:
        self.generator = generator
        self.ledger = ledger
        self.skill_directory = Path(skill_directory).expanduser().resolve()
        self.recommender = SkillRecommender()

    def run(
        self,
        trace: AgentTrace,
        repository: str | Path,
        verification_plan: PatchVerificationPlan,
        *,
        promote: bool = False,
        skill_limit: int = 5,
    ) -> AutoFixPipelineResult:
        source = Path(repository).expanduser().resolve()
        recommendation = self.recommender.recommend(
            trace,
            self.skill_directory,
            repository_path=source,
            limit=skill_limit,
            allow_missing_directory=True,
        )
        context = PatchGenerationContext(
            trace=trace,
            diagnosis=recommendation.diagnosis,
            code_locations=recommendation.code_locations,
            skill_matches=recommendation.skills.matches,
        )
        generated = self.generator.generate(source, context)
        protected_paths = list(
            dict.fromkeys(
                [
                    *verification_plan.protected_paths,
                    *self.generator.protected_paths(source),
                ]
            )
        )
        effective_plan = verification_plan.model_copy(update={"protected_paths": protected_paths})
        experience = self._experience(recommendation, generated.provider, effective_plan)
        evolution = EvolutionPipeline(self.ledger, self.skill_directory).run(
            source,
            generated.patch,
            effective_plan,
            experience,
            promote=promote,
        )
        return AutoFixPipelineResult(
            recommendation=recommendation,
            generated_patch=generated,
            evolution=evolution,
        )

    @staticmethod
    def _experience(
        recommendation: SkillRecommendationResult,
        provider: str,
        plan: PatchVerificationPlan,
    ) -> RepairExperience:
        diagnosis = recommendation.diagnosis
        components = list(
            dict.fromkeys(
                location.symbol
                for location in recommendation.code_locations
                if location.kind != "file"
            )
        )
        trigger_terms = diagnosis.search_terms or [diagnosis.failure_type.value]
        root_cause = diagnosis.likely_causes[0] if diagnosis.likely_causes else diagnosis.summary
        validation_steps = [
            *(f"Run benchmark command: {command.name}" for command in plan.commands),
            *(f"Enforce evaluation metric: {rule.metric}" for rule in plan.policy.rules),
        ]
        return RepairExperience(
            title=f"Autofix {diagnosis.failure_type.value.replace('_', ' ')}",
            failure_type=diagnosis.failure_type,
            trigger_terms=trigger_terms[:16],
            root_cause=root_cause,
            repair_steps=[f"Apply the unified diff generated by {provider}"],
            validation_steps=validation_steps,
            affected_components=components,
        )
